### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by elhcarelog** [Undead34/ffmpeg-static-electron-forge#1]
I get this error on a intel chip but when running on arm there is no error:

Uncaught Exception:
Error: spawn Unknown system error -86
at ChildProcess.spawn (node:internal/child_process:413:11)
at spawn (node:child_process:783:9)
at /Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:231338
at e._getFfmpegPath (/Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:211918)
at e._spawnFfmpeg (/Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:231097)
at e.availableFormats.e.getAvailableFormats (/Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:215589)
at /Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:216005
at r (/Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:250908)
at Immediate.<anonymous> (/Applications/Carelog.app/Contents/Resources/app.asar/.webpack/main/index.js:2:249921)
at process.processImmediate (node:internal/timers:476:21)

**Comment by Undead34** [comment]
The error you're encountering, spawn Unknown system error -86, is indicative of a binary incompatibility issue on your Intel-based machine when using a binary compiled for a different architecture, such as ARM. Specifically, the issue is occurring when a child process is spawned to run ffmpeg, suggesting that the ffmpeg binary being used is not compatible with your current architecture.

What happens is that the binaries I download are for x86_64 so, go into the node_modules folder, look for this library and replace it with your binaries.

```bash
X:\MyApp\node_modules\ffmpeg-static-electron-forge\dist\bin\win32\x64\ffmpeg.exe
X:\MyApp\node_modules\ffmpeg-static-electron-forge\dist\bin\win32\x64\ffprobe.exe
```

Probably if I have time I can add that support, and improve the library that I have abandoned.

**Comment by elhcarelog** [comment]
Sounds good. Thank you I will give it a try.
